spring:
  datasource:
    username: sa
    password: 584520
    url: jdbc:mysql://192.168.31.3:3306/jdbc?serverTimezone=UTC&characterEncoding=UTF-8&userUnicode=true
    driver-class-name: com.mysql.jdbc.Driver



mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.atguigu.springboot.entities
